# -*- coding: utf-8 -*-
"""atbs.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1MzcxVoPA2CGy4ac_Y4Gv8Ur2MD4Dj6lC
"""

def gradingStudents(grades):
  # Getting the numbers seperatly
  for i in range(len(grades)):
      # Grades lower then 38 are failing even with the round up so we skip them
      if grades[i] >= 38:
          # To get the next multiple of 5 we find the remainer of the grade and add 5
          nxt = grades[i] - (grades[i]%5) + 5
          # To get differance between multiple of 5 and the grade we munus the round up with the grade
          dif = nxt - grades[i]
          
          # If the differance is lower then 3 we use the round up
          if dif < 3:
              grades[i] = nxt
  return grades